### ISSUE TITLE
Use ledgetech/lua-resty-http?

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#14]
I see the project is using [`api7-lua-resty-http`](https://github.com/yangxikun/opentelemetry-lua/blob/b384f7b4f7a90db6cc5c5e1473667ad691a69f2a/rockspec/opentelemetry-lua-master-0.1-3.rockspec#L16). That project is a fork of https://github.com/ledgetech/lua-resty-http, which seems better maintained. 

Is there a reason the project is using the api7 fork? If not, would the maintainers accept a PR moving to use the original `ledgetech` rock?

![Screen Shot 2022-07-07 at 3 13 06 PM](https://user-images.githubusercontent.com/370182/177872445-28ccc52c-68d5-45d4-8c92-197b1218fb66.png)

**Comment by yangxikun** [comment]
PR is welcome.
