### ISSUE TITLE
Support Baggage headers

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#20]
OpenTelemetry supports interaction with baggage [see baggage headers w3c spec](https://www.w3.org/TR/baggage/). 

We should implement this in opentelemetry-lua.

- [Baggage Signal](https://github.com/open-telemetry/opentelemetry-specification/blob/ca593258953811eb33197976b8e565299b874853/specification/overview.md#baggage-signal)
- [Baggage API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md)

I think the three bits of work are:

- [x] write baggage text map propagator (inject/extract)
- [x] add capability to add/remove baggage within SDK (get value, remove value, get all values, remove value)
- [x] add ability to add/remove baggage from Context

**Comment by yangxikun** [comment]
Welcome PR, thanks.

**Comment by plantfansam** [comment]
Related PR: https://github.com/yangxikun/opentelemetry-lua/pull/24

**Comment by yangxikun** [comment]
🎉🎉🎉
