### ISSUE TITLE
Remove inactive_timeout assertion?

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#26]
In `baggage_span_processor.new`, we [assert](https://github.com/yangxikun/opentelemetry-lua/blob/8adf7260e77380dc4f924eaccaab22bac9c42296/lib/opentelemetry/trace/batch_span_processor.lua#L116) that `inactive_timeout` is `> 0`. Is this necessary? Are we concerned about overwhelming collectors?

**Comment by yangxikun** [comment]
`batch_span_processor` is create once in `init_worker_by_lua_block`, so I think the assertions is cheap.

**Comment by plantfansam** [comment]
Yes, but do you think someone might want to run with `inactive_timeout` set to `0`?

**Comment by yangxikun** [comment]
If `inactive_timeout ` set to 0, maybe will trigger useless timer callback when `#self.batch_to_process == 0 and #self.queue > 0`, you can review the code of `flush_batches`.
