### ISSUE TITLE
TraceContext propagator should return unmodified context if header is not present

### ISSUE THREAD

**Issue by kamalmarhubi** [yangxikun/opentelemetry-lua#34]
Pretty sure this is the culprit line: https://github.com/yangxikun/opentelemetry-lua/blob/1029740407218757be58b3914e8bb5b24559cdb6/lib/opentelemetry/trace/propagation/text_map/trace_context_propagator.lua#L197

That should be
```
return context
```

This is in [the spec](https://opentelemetry.io/docs/reference/specification/context/api-propagators/#extract):
> If a value can not be parsed from the carrier, for a cross-cutting concern, the implementation MUST NOT throw an exception and MUST NOT store a new value in the Context, in order to preserve any previously existing valid value.

See also, eg, the Python implementation, which returns the unmodified context if the header is not present or contains invalid content: https://github.com/open-telemetry/opentelemetry-python/blob/75313b6c6d58945c1401622b6683ccdd28657984/opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py#L51-L70

I came across this because I wrote a custom propagator for Google's x-cloud-trace-context header. Using that together with the tracecontext propagator via the composite propagator resulted in an empty context if only one of the headers was specified.

**Comment by plantfansam** [comment]
Nice catch! I think you are correct.

**Comment by yangxikun** [comment]
LGTM
