### ISSUE TITLE
Add tracestate to exports

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#38]
We're hard-coding an empty string for `tracestate` when we [encode spans for export](https://github.com/yangxikun/opentelemetry-lua/blob/main/lib/opentelemetry/trace/exporter/encoder.lua#L41). Unless I'm missing something, we should pass tracestate along to the exporter (see [trace proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L104)).

**Comment by yangxikun** [comment]
Review this PR: https://github.com/yangxikun/opentelemetry-lua/pull/41

**Comment by yangxikun** [comment]
@plantfansam Please review this PR: https://github.com/yangxikun/opentelemetry-lua/pull/41

**Comment by plantfansam** [comment]
Sorry for the delay @yangxikun, I was away - PR looks good!
