### ISSUE TITLE
should_sample should receive a full context object, not span context

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#48]
Per the specification, the tracer should pass a [full `context`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md) object to `should_sample`. [Currently, the tracer passes `span_context`](https://github.com/yangxikun/opentelemetry-lua/blob/main/lib/opentelemetry/trace/tracer.lua#L35-L41).

We should update `new_span` to pass the whole `context` object and  update the [samplers](https://github.com/yangxikun/opentelemetry-lua/tree/main/lib/opentelemetry/trace/sampling) to match.

**Comment by yangxikun** [comment]
Yes, this should fix.

**Comment by rdooley** [comment]
took a stab at this [here](https://github.com/yangxikun/opentelemetry-lua/pull/49) along with what I think is a minor doc string correction

**Comment by rdooley** [comment]
I believe this is done now and can be closed with the merge of #49

**Comment by plantfansam** [comment]
Yes, thanks @rdooley!
