### ISSUE TITLE
unprocessed spans can be loosed after nginx is reloaded

### ISSUE THREAD

**Issue by wangrzneu** [yangxikun/opentelemetry-lua#5]
Currently, all pending processed spans are stored in a field in the batch_span_processor object, so unprocessed spans can be loosed after Nginx is reloaded.
I think a shared dict based spans processor should be implemented which can be used in above scenario. And I can try to implement it.

**Comment by yangxikun** [comment]
Could you implement it as alternative choice? If the shared dict is configured, then use shared dict, otherwise  backoff to local var.

**Comment by wangrzneu** [comment]
That is ok. I am working on it.
