### ISSUE TITLE
Add ability to manipulate tracestate

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#50]
Currently, we parse inbound [tracestate headers into a validated string](https://github.com/yangxikun/opentelemetry-lua/blob/5d68c4248e1b4a486320ad6da0be13ab1d02f47b/lib/opentelemetry/trace/propagation/text_map/trace_context_propagator.lua#L89), but we don't allow users to set `tracestate` values. Per the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/tracestate-handling.md#setting-values), SDKs should offer the ability to set `tracestate` values. 

I think we should introduce a `tracestate` module and parse the header into an instance of that module. Then the module would offer facilities for setting values. I think we'd need to add logic to tracestate module to serialize its internal storage to `tracestate` header format and invoke this method from the text map propagator's [`inject` method](https://github.com/yangxikun/opentelemetry-lua/blob/5d68c4248e1b4a486320ad6da0be13ab1d02f47b/lib/opentelemetry/trace/propagation/text_map/trace_context_propagator.lua#L36) at some point. 

Reference: https://www.w3.org/TR/trace-context/#tracestate-header

**Comment by yangxikun** [comment]
approve
