### ISSUE TITLE
Release 0.2-2

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#52]
👋  would love a release to get new changes into the wild @yangxikun!

Diff: https://github.com/yangxikun/opentelemetry-lua/compare/v0.2.1...main

**Comment by yangxikun** [comment]
We can release after https://github.com/yangxikun/opentelemetry-lua/pull/53 merged.

**Comment by plantfansam** [comment]
Mentioned this on #53, but I think we're good to merge and release 😄

**Comment by yangxikun** [comment]
🎉  [0.2-2](https://luarocks.org/modules/yangxikun/opentelemetry-lua/0.2-2)

**Comment by plantfansam** [comment]
Thanks @yangxikun!
