### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by boekkooi-lengoo** [yangxikun/opentelemetry-lua#60]
Good day,
I'm currently using the opentelemetry plugin in APISix in combination with Elastic APM which is served over https.
Sadly I can't seem to get this to work as the `address` gets prefixed with `http://` in the [http_client](https://github.com/yangxikun/opentelemetry-lua/blob/main/lib/opentelemetry/trace/exporter/http_client.lua#L23).

This results in the following error.
```
2023/01/25 10:55:29 [error] 51#51: *5451 [lua] http_client.lua:46: do_request(): request failed: Client sent an HTTP request to an HTTPS server.
, context: ngx.timer, client: 10.20.0.68, server: 0.0.0.0:9443
```

Is it possible to add support for https or at least only prefix the address when it contains no protocol?

Thanks in advance.

Related to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options and the env var `OTEL_EXPORTER_OTLP_ENDPOINT`

**Comment by yangxikun** [comment]
I will try to implement this feature.

**Comment by yangxikun** [comment]
@boekkooi-lengoo Do you need config `ssl_verify = false`, see https://github.com/ledgetech/lua-resty-http/blob/2af9925acf5cbb5b387539cd4463552ebbd5efee/lib/resty/http_connect.lua#L30

**Comment by boekkooi-lengoo** [comment]
Hey @yangxikun,
Thank for for having a look at this issue.
I think allowing the user to configure `ssl_verify` would be great, however in my case I don't need it :smile:

**Comment by yangxikun** [comment]
https://github.com/apache/apisix/pull/8823 is merged.

**Comment by boekkooi-lengoo** [comment]
Hey @yangxikun,
Thank you for resolving this issue and even getting it into APISIX amazing :partying_face:!
