### ISSUE TITLE
Add release process and changelog

### ISSUE THREAD

**Issue by plantfansam** [yangxikun/opentelemetry-lua#62]
As the library evolves, we make breaking changes. I think we should create a release process and publish a changelog for every release. I am happy to make a proposal and build automation, but wanted to see if people are interested.

**Comment by yangxikun** [comment]
Approve, there are already had [CHANGELOG.md](https://github.com/yangxikun/opentelemetry-lua/blob/main/CHANGELOG.md)

**Comment by plantfansam** [comment]
🤦  my bad.
