### ISSUE TITLE
Baggage header parsing regex missing whitespace

### ISSUE THREAD

**Issue by x48zhu** [yangxikun/opentelemetry-lua#77]
Hello, 
While I'm looking at how key-value pairs are parsed from the baggage header [here](https://github.com/yangxikun/opentelemetry-lua/blob/main/lib/opentelemetry/baggage/propagation/text_map/baggage_propagator.lua#L90), I think it include the space and tab, which are valid characters according to the [doc](https://www.w3.org/TR/baggage/#definition), in the key or value.

For example, if I have a baggage header whose content is "key = value", the current behavior returns "key " and " value" (including the whitespace).

I think a better Regex expression could be `(%S+)%s*=%s*(%S+)`

**Comment by yangxikun** [comment]
`Leading and trailing whitespaces (OWS) are allowed and are not considered to be a part of the key.`
`Leading and trailing whitespaces (OWS) are allowed and are not considered to be a part of the value.`

I think we can trim the key and value after split.

**Comment by x48zhu** [comment]
Yeah, that should work too.
Or you could try the Regex expression `(%S+)%s*=%s*(%S+)` I think it works correctly for me.
Either way is fine!
