### ISSUE TITLE
Support array_value attribute type

### ISSUE THREAD

**Issue by fularac** [yangxikun/opentelemetry-lua#82]
Would be helpful for sending the the `header.(request|response).header.<key>` for following the http conventions: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-request-and-response-headers

### HTTP request and response headers

| Attribute  | Type | Description  | Examples  | Requirement Level |
|---|---|---|---|-------------------|
| `http.request.header.<key>` | string[] | HTTP request headers, `<key>` being the normalized HTTP Header name (lowercase, with `-` characters replaced by `_`), the value being the header values. [1] [2] | `http.request.header.content_type=["application/json"]`; `http.request.header.x_forwarded_for=["1.2.3.4", "1.2.3.5"]` | Opt-In            |
| `http.response.header.<key>` | string[] | HTTP response headers, `<key>` being the normalized HTTP Header name (lowercase, with `-` characters replaced by `_`), the value being the header values. [1] [2] | `http.response.header.content_type=["application/json"]`; `http.response.header.my_custom_header=["abc", "def"]` | Opt-In            |

P.S. thank you for all your work so far!

**Comment by yangxikun** [comment]
Do you mean add two method to get http header attributes for span, just like golang sdk:

https://github.com/open-telemetry/opentelemetry-go/blob/f15ae160c4acfe3872455f87e6133af87859172b/semconv/internal/v4/http.go#L299

https://github.com/open-telemetry/opentelemetry-go/blob/f15ae160c4acfe3872455f87e6133af87859172b/semconv/internal/v4/http.go#L304

**Comment by fularac** [comment]
Those helper functions would be useful too! 

Looking into the [ppentelemetry/attribute.lua](https://github.com/yangxikun/opentelemetry-lua/blob/main/lib/opentelemetry/attribute.lua) it's missing the `<type>Slice` versions as found in https://github.com/open-telemetry/opentelemetry-go/blob/69611bd01a355466f324cca84068f54e6e388654/attribute/value.go#L40-L59
