### ISSUE TITLE
[feature request]: tailsampling support

### ISSUE THREAD

**Issue by zxyao145** [yangxikun/opentelemetry-lua#83]
Hi, is tail sampling predictable? Full sampling for 5xx requests and ratio sampling for other requests, it has a greater meaning in practice.

**Comment by zxyao145** [comment]
@yangxikun Hi, how should I use it? I didn't see tailsampler under https://github.com/yangxikun/opentelemetry-lua/tree/main/lib/opentelemetry/trace/sampling

**Comment by plantfansam** [comment]
I think "tail sampling" is properly done within the collector, when you are tail sampling _the entire trace_. 

If you want to make decisions about keeping or dropping OpenResty spans _after_ OpenResty gets a response back from upstream, I've had luck writing a custom span processor that keeps the spans until OpenResty's log phase, then throws them away or keeps them based on the response code from upstream.

See also https://github.com/open-telemetry/opentelemetry-specification/issues/2914

**Comment by zxyao145** [comment]
@yangxikun @plantfansam Get it, thank you for your reply!
