### ISSUE TITLE
Support for Custom URI with OpenTelemetry SDK

### ISSUE THREAD

**Issue by orrn** [yangxikun/opentelemetry-lua#99]
Hello,

I am currently using APISIX version 3.9.1 and have integrated opentelemetry.lua for tracing purposes. My setup involves using Alibaba Cloud's collector, which does not utilize the default /v1/traces URI for trace collection.

I would like to request the ability to customize the URI used for sending traces in the OpenTelemetry plugin. This feature would greatly enhance the flexibility of APISIX's tracing capabilities, especially for those of us using different backends or cloud providers that may not adhere to the default URI paths.

Thank you for considering this enhancement.

**Comment by orrn** [comment]
https://github.com/yangxikun/opentelemetry-lua/pull/100

**Comment by yangxikun** [comment]
Does PR #101 fix this issue?
You can set a custom URI path in the address parameter, such as `http://aaa.com/another/traces`.

**Comment by orrn** [comment]
This is exactly what I wanted. Thank you very much.
